### PR TITLE
Use alias for Omega_h_vector.

### PR DESCRIPTION
**Pull request by jacobmerson**
This pull request replaces the `Vector` class with an alias for `Few`. The current implementation of `Vector` is essentially just an alias with the addition of `operator()`.

### CODE REVIEW

**Comment by jacobmerson** [comment]
@ibaned how do you feel about this change as well? If you aren't a fan of this I'll put a pull request for marking the `Vector` `initializer_list` constructor `OMEGA_H_INLINE` as well. This was already done on the SCOREC version so I missed this change here.

**Comment by ibaned** [comment]
Interesting... this does seem to save code! Do you really need the volatile overloads? The latest version of Kokkos doesn't require volatile overloads for the result of reductions.

**Comment by jacobmerson** [comment]
@ibaned I don't think the volatile overloads were needed, but I wasn't positive why they were there, so I was nervous to remove them...If you want I can take out the volatile overloads and run the tests with Kokkos+Cuda.

**Comment by ibaned** [comment]
Yea that would be great! If all that passes this seems like a useful change.

**Comment by jacobmerson** [comment]
@ibaned this passed the omega_h test suite for both Kokkos+Cuda and Kokkos+OpenMP on my workstation.

**Pull request merged**
