### PR TITLE
fix `form_barycentric` add function for mapping global coords to barycentric coords

### PR DESCRIPTION
**Pull request by jacobmerson**
The form barycentric function assumes that the basis from simplex_basis
is giving the xi_0 and xi_1 coordinates, but in reality, it is giving
the xi_1, and xi_2 coordinates. Thus the resulting coordinates from
form_barycentric are rotated.

This pull request is in support of the error described in #389 .

### CODE REVIEW

**Comment by jacobmerson** [comment]
@ibaned as per our discussion in #389 I did the following:

1. Fix `form_barycentric` to be consistent with the `simplex_basis`
2. Create function `barycentric_from_global` to get the barycentric coordinates from the global coordinates
3. replace code in the transfer and confided files to use the new `barycentric_from_global` function.

The `warp_test` which looks like it uses the transfer is now failing in it's comparison to the "gold" mesh. I think this is because it was running into the bug from inconsistency in `form_barycentric` in the original mesh.

**Comment by ibaned** [comment]
I agree about warp test, I think it is fine to delete the old "gold" mesh.

**Comment by jacobmerson** [comment]
If I delete the gold mesh from before I made the changes to `form_barycentric` then everything passes.

**Comment by jacobmerson** [comment]
@ibaned let me know if there is anything else I should do to merge this. The test I added is pretty minimal, but it will at least catch if incorrect barycentric coordinates are computed from the real coordinates within the triangle.

**Pull request merged**
